<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NSwag.AspNetCore" Version="14.1.0" />
		
		<!-- take versions from https://github.com/ppy/osu-queue-score-statistics/blob/master/osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj -->
        <!-- master branch on the osu-queue-score-statistics should reflect what is currently running on osu servers after a diffcalc/pp reprocess has happened -->
        <PackageReference Include="ppy.osu.Game" Version="2025.1013.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Catch" Version="2025.1013.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Mania" Version="2025.1013.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2025.1013.0" />
        <PackageReference Include="ppy.osu.Game.Rulesets.Taiko" Version="2025.1013.0" />
	</ItemGroup>

</Project>